# Application name
spring.application.name=pet-adopt

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pet_adoption_platform
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.thymeleaf.check-template-location=true